### PR TITLE
refactoring/codeclimate

### PR DESCRIPTION
**Pull request by Brantron**
will be pushing commits

### CODE REVIEW

**Comment by Brantron** [comment]
https://codeclimate.com/github/instacart/Snacks/compare/brantron/refactor#ratings

**Comment by Brantron** [comment]
I would say it was 50/50. I feel like a tool like this is great as an overall guide but I don't think striving for all A's should be the goal (not that anyone stated it is the goal). There were some improvements I made that felt good but to get rid of all of the issues I definately felt I was refactoring for the tool vs maintainability and readibility. Code golf is fun but I felt like I was code golfing vs trying to improve a shared lib. I think I would prefer to go back and reintroduce some offenders before merging this.

**Comment by Brantron** [comment]
I will push a few more commits later. They will reduce the file scores but I'm curious where the happy medium falls. Maybe a B or greater is a good goal.

**Comment by dcocchia** [comment]
Great feedback :) If you remove some of the code changes, let’s keep track of which rules seem arbitrary or too strict. We can change the code climate config to match our needs

**Comment by Brantron** [comment]
Hmm, I reintroduced some of the code that was offending before and it's no longer an issue... I was definitely getting hits on too many return statements and too many args for a function. These are good rules overall and I think we would get value in keeping them.

**Comment by dcocchia** [comment]
Interesting 🤔 Well, I think we can safely merge and keep track of our feelings on the code climate reports with future PRs to adjust how strict the rules are

**Pull request merged**
