### PR TITLE
Adding support for <Table/>

### PR DESCRIPTION
**Pull request by tmarshall**
Adding support for `<Table/>`

```jsx
<Table
  data={[
    { name: 'Apple', title: 'fruit' },
    { name: 'Carrot', title: 'vegetable' },
    { name: 'Lemon', title: 'fruit' },
    { name: 'Avocado', title: 'VEGETABLE' }
  ]}
  definition={[
    { header: 'Name', attribute: 'name' },
    { header: 'Title', attribute: 'title', cellRender: (name, rowIndex, rowData) => (<span>{name.toLowerCase()}</span>) }
  ]}
/>
```

returns

screen shot 2018-09-17 at 5 33 27 pm

### CODE REVIEW

**Comment by michalDob** [comment]
Does this match what our design team want to do with tables ? I noticed it looks nothing like tables in RPP :(

**Comment by tmarshall** [comment]
From Slack conversation:

- [ ] update header styles
- [ ] allow for draggable column widths
- [ ] ensure header content can be custom components
- [ ] allow option for table to be full-bleed (if 100% width in a container)
- [ ] explore better responsive layouts
- [ ] allow empty rows & columns, if needed

**Comment by tmarshall** [comment]
^ i am not sure if we need to support colspans....

**Comment by tmarshall** [comment]
this is fairly old - and not going to be used by Ads any more - closing it out

**Pull request closed without merging**
