### PR TITLE
Logan/add button aria label

### PR DESCRIPTION
**Pull request by logtheman**
Add aria label props to the Button component for accessibility.
@julianhr

### CODE REVIEW

**Comment by dcocchia** [comment]
@julianhr Can you take a look at this one when you get a chance?

@logtheman Can you rebase with master to ensure we can merge when we're ready?

**Comment by wfro** [comment]
This was why we originally included `elementAttributes`, for any other arbitrary attrs that a button might need. If we wanted to do this as just a convenience API, I'd vote for `ariaLabel` as a string.

**Comment by logtheman** [comment]
@wfro - Maybe we need to revisit the implementation in other components and decide on a consist method. Radio Button implements using aria as an object with a label attribute, which is the pattern I followed here after discussing with @julianhr. However, Circle Button uses `ariaLabel` as you suggested. Right now we don't have consistency. We should agree on a standard.

**Comment by wfro** [comment]
@logtheman yep agreed on consitency. Since `ariaLabel` is the most common thing that would be added to `elementAttributes`, that's my vote (and we can change the Radio api, and and it to the `Button` api.

**Comment by dcocchia** [comment]
We're to the point with Snacks now that we can start hardening our API, but we'll need to agree on what it should be. There are a couple things we need to get consistency on that I think we should talk through. Like `style` vs `styles` prop. We also have been talking about standardizing our event handing system. I'll spin up a Snacks specific Slack room so we can start talking through these kinds of things.

**Comment by julianhr** [comment]
My two cents is that aria attributes vary a lot depending on context. Therefore, a flexible system is needed. Doing a simple search for aria usage in our codebase yields this:

screen shot 2018-01-11 at 12 00 14 pm

aria-hidden
aria-describedby
aria-label

These were only the first top results. The reason I opted for the Shape is that the attributes are diverse and aria is always the prefix. Therefore, my vote would be for the shape. Agree that we need to come up with a consistent method of describing them.

**Comment by wfro** [comment]
I'm gonna change my mind here and advocate for `elementAttributes`, it's original intention was to be a flexible way to add these kinds of html attributes. If we make sure the rest of the component's API has what it needs, I'm not too worried about `elementAttributes` being a junk drawer.

**Comment by logtheman** [comment]
Closing in favor of spreading unspecified props rather than specifying a aria object.

**Comment by julianhr** [comment]
@loganmurdock I think it would be better to use this PR for the changes you will make so that, when merged, if ever needed we can refer back to this conversation searching through the PR history. This has been helpful in the past for me.

**Pull request closed without merging**
