### PR TITLE
scrollWidth causing incorrect calculatePosition

### PR DESCRIPTION
**Pull request by cliewdevelop**
proposing to change to offsetWidth

### CODE REVIEW

**Comment by cliewdevelop** [comment]
Screen Shot 2021-07-27 at 10 40 22 AM

Screen Shot 2021-07-27 at 10 40 28 AM

**Comment by cliewdevelop** [comment]
When this.calculatePosition happens the first time, because we are using scrollWidth, the offset doesn't get calculate properly. The tooltip pops open to the right, and creates more space to the right, and auto scrolls there. (or it may not, depending on OS setting)

**Comment by cliewdevelop** [comment]
Screen Shot 2021-07-27 at 10 42 29 AM

Screen Shot 2021-07-27 at 10 42 22 AM

*note: the orange blocks are intentionally hardcoded to visualize where the target dom for clicking is

**Comment by cliewdevelop** [comment]
Afterwards, when scrollWidth becomes correct, this doesn't happen again. 
With the wrong scrollWidth, the calculation if block doesn't get triggered.

> else if (overlayDistanceFromRightEdge > documentWidth) {
https://github.com/instacart/Snacks/blob/master/src/components/Tooltip/TooltipPosition.js#L89


So far in debugging offsetWidth has been the correct width to use to trigger things

**Review by mmarcuccio — APPROVED** [review]

**Pull request merged**
