### PR TITLE
Fix node environment

### PR DESCRIPTION
**Pull request by dcocchia**
[Webpack has some issues](https://github.com/webpack/webpack/issues/6522) exporting packages that can work in a both a browser and node environment. This is a workaround for that, plus some added verification steps for the build script.

### CODE REVIEW

**Comment by tmarshall** [comment]
> $ npm run release:verifyBuild

> ic-snacks@0.0.95 release:verifyBuild /Users/timmarshall/repos/Snacks
> babel-node scripts/release/verify_build.js

> sh: babel-node: command not found

**Comment by tmarshall** [comment]
^ do i not have `-g` babel cli on my machine?? 😦

**Comment by tmarshall** [comment]
lgtm

**Comment by dcocchia** [comment]
Hey @nebrelbug - can you show me the error you're seeing?

**Comment by nebrelbug** [comment]
@dcocchia sorry, I followed a link from the Webpack issue and for some reason I thought this was the Webpack repo. Your fix looks like it will solve my problem though! Thanks!

**Pull request merged**
